# Generated by Django 5.2.7 on 2025-11-01 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('course_name', models.CharField(max_length=255)),
                ('teacher_ids', models.JSONField(default=list, help_text='List of teacher UIDs')),
                ('teacher_names', models.JSONField(default=list, help_text='List of teacher full names')),
                ('student_roll_numbers', models.JSONField(default=list, help_text='List of student roll numbers')),
                ('num_students_registered', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['course_name'],
                'indexes': [models.Index(fields=['course_name'], name='core_course_course__79c890_idx')],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_id_copy', models.CharField(editable=False, max_length=50)),
                ('course_name', models.CharField(editable=False, max_length=255)),
                ('teacher_name', models.CharField(editable=False, max_length=150)),
                ('present_roll_numbers', models.JSONField(default=list, help_text='List of roll numbers present')),
                ('absent_roll_numbers', models.JSONField(default=list, help_text='List of roll numbers absent')),
                ('num_students_attended', models.IntegerField(default=0)),
                ('num_students_absent', models.IntegerField(default=0)),
                ('session_created', models.DateTimeField(auto_now_add=True)),
                ('session_ended', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='core.course')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions_taught', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-session_created'],
                'indexes': [models.Index(fields=['course', 'session_created'], name='core_sessio_course__19a3e5_idx'), models.Index(fields=['teacher', 'session_created'], name='core_sessio_teacher_e2f649_idx')],
            },
        ),
    ]
