# Generated by Django 5.2.7 on 2025-11-02 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_course_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='attendance_portal_status',
            field=models.CharField(choices=[('ON', 'On'), ('OFF', 'Off')], default='ON', max_length=3),
        ),
    ]
